#so adding it in config server so all the services can use it -> reducing the redundant code
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

okta:
  oauth2:
    issuer: https://dev-94506845.okta.com/oauth2/default
    audience: api://default
